"""add settler_activity to incident type

Revision ID: 0c9b997dc15c
Revises: 7ee30cb0982e
Create Date: 2026-04-18 11:12:44.106548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9b997dc15c'
down_revision: Union[str, Sequence[str], None] = '7ee30cb0982e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
