"""replace delay with traffic in incident type

Revision ID: 3fd0b194e3a6
Revises: 0c9b997dc15c
Create Date: 2026-04-18 12:00:16.037102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd0b194e3a6'
down_revision: Union[str, Sequence[str], None] = '0c9b997dc15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
